package com.alpha.commun;

public class Duha
{
/*
 * 
 * 
-- Chapitre 1 - Le mérite de l'invocation
-- Chapitre 2 - Lorsqu'on se réveille
-- Chapitre 3 - Lorsqu'on s'habille
-- Chapitre 4 - Lorsque l'on met un vêtement neuf
-- Chapitre 5 - Ce que l'on dit à celui qui met un vêtement neuf
-- Chapitre 6 - Avant de se déshabiller
-- Chapitre 7 - En entrant aux toilettes
-- Chapitre 8 - En sortant des toilettes
-- Chapitre 9 - Ce que l'on dit avant les ablutions
-- Chapitre 10 - Ce que l'on dit après les ablutions
-- Chapitre 11 - En entrant/sortant de la maison
-- Chapitre 12 - En allant à la mosquée
-- Chapitre 13 - En entrant à la mosquée
-- Chapitre 14 - En sortant de la mosquée
-- Chapitre 15 - De l'appel à la prière
-- Chapitre 16 - De l'ouverture de la prière
-- Chapitre 17 - De l'inclinaison
-- Chapitre 18 - En se redressant de l'inclinaison
-- Chapitre 19 - De la prosternation
-- Chapitre 20 - Entre les deux prosternations
-- Chapitre 21 - De la prosternation de la récitation du Coran
-- Chapitre 22 - L'attestation de foi
-- Chapitre 23 - La prière sur le Prophète (saws) après l'attestation de foi
-- Chapitre 24 - Après le dernier Tachahhud juste avant les salutations
-- Chapitre 25 - Après la prière
-- Chapitre 26 - De la prière dite de consultation (al-Istikhâra)
-- Chapitre 27 - Du matin et du soir
-- Chapitre 28 - Du sommeil
-- Chapitre 29 - Lorsque l'on change de côté en dormant
-- Chapitre 30 - Lorsque l'on se réveille en sursaut ou que l'on se sent mal
-- Chapitre 31 - Ce que l'on doit faire après un songe ou un cauchemar
-- Chapitre 32 - Du Qunût dans la prière du Witr
-- Chapitre 33 - Après la prière du Witr
-- Chapitre 34 - En cas de soucis et de tristesse
-- Chapitre 35 - En cas d'affliction
-- Chapitre 36 - En rencontrant l'ennemi ou des autorités
-- Chapitre 37 - De celui qui craint l'injustice du gouverneur
-- Chapitre 38 - Contre l'ennemi
-- Chapitre 39 - De celui qui craint un groupe de gens
-- Chapitre 40 - De celui qui rencontre des doutes dans sa croyance
-- Chapitre 41 - Pour se délivrer d'une dette
-- Chapitre 42 - Contre la tentation dans la prière et au cours de la récitation du Coran
-- Chapitre 43 - Lorsque l'on rencontre une difficulté
-- Chapitre 44 - Lorsque l'on a commis un péché
-- Chapitre 45 - Ce qui chasse le diable et ses tentations
-- Chapitre 46 - Lorsqu'il arrive une chose désagréable ou que l'on est dépassé par les événements
-- Chapitre 47 - Les félicitations à l'occasion d'une naissance
-- Chapitre 48 - Pour demander la protection d'Allah sur les enfants
-- Chapitre 49 - Ce que l'on dit en visitant un malade
-- Chapitre 50 - Le mérite de rendre visite à un malade
-- Chapitre 51 - Du malade qui perd espoir de vivre
-- Chapitre 52 - Faire prononcer au mourant la profession de foi (ach-Chahâda)
-- Chapitre 53 - De celui qui est atteint par un malheur
-- Chapitre 54 - Après avoir fermé les yeux du mort
-- Chapitre 55 - Pour le mort pendant l'office funéraire
-- Chapitre 56 - Pour l'enfant mort lors de la prière sur lui
-- Chapitre 57 - Les condoléances
-- Chapitre 58 - En plaçant le mort dans sa tombe
-- Chapitre 59 - Après l'inhumation du mort
-- Chapitre 60 - En visitant le cimetière
-- Chapitre 61 - Lorsque le vent souffle
-- Chapitre 62 - Lorsque le tonnerre gronde
-- Chapitre 63 - Parmi les invocations de demande de pluie
-- Chapitre 64 - Lorsque la pluie tombe
-- Chapitre 65 - Après la pluie
-- Chapitre 66 - Lorsque l'on a peur de la pluie
-- Chapitre 67 - En voyant la nouvelle lune
-- Chapitre 68 - Au moment de rompre le jeûne
-- Chapitre 69 - En commençant le repas
-- Chapitre 70 - A la fin du repas
-- Chapitre 71 - De l'invité en faveur de l'hôte
-- Chapitre 72 - En faveur de celui qui donne à boire
-- Chapitre 73 - Du jeûneur en faveur de celui qui lui fait rompre
-- Chapitre 74 - Du jeûneur lorsqu'on lui présente à manger et qu'il ne rompt pas son jeûne
-- Chapitre 75 - Ce que doit dire le jeûneur lorsqu'il se fait injurier
-- Chapitre 76 - Ce que l'on dit lorsque l'on voit les premiers fruits
-- Chapitre 77 - De l'éternuement
-- Chapitre 78 - Ce que l'on dit au mécréant lorsqu'il loue Allah après avoir éternué
-- Chapitre 79 - En faveur du nouveau marié
-- Chapitre 80 - De celui qui se marie ou achète une monture
-- Chapitre 81 - Avant les rapports sexuels
-- Chapitre 82 - Dans les moments de colère
-- Chapitre 83 - Lorsque l'on voit une personne éprouvée
-- Chapitre 84 - Ce qui est dit dans une assemblée
-- Chapitre 85 - L'expiation du verbiage dans une assemblée
-- Chapitre 86 - En faveur de celui qui dit 'qu'Allah te pardonne'
-- Chapitre 87 - En faveur de celui qui rend un service
-- Chapitre 88 - Les choses par lesquelles Allah préserve de l'Antéchrist
-- Chapitre 89 - En faveur de celui qui dit 'je t'aime en Allah'
-- Chapitre 90 - En faveur de celui qui propose le don de ses biens
-- Chapitre 91 - De celui qui s'acquitte de ses dettes en faveur de celui qui lui a accordé
-- Chapitre 92 - Lorsque l'on craint le polythéisme (ach-Chirk)
-- Chapitre 93 - En faveur de celui qui dit 'qu'Allah te bénisse'
-- Chapitre 94 - Du mauvais présage
-- Chapitre 95 - En enfourchant une monture ou en empruntant un moyen de transport
-- Chapitre 96 - Du voyage
-- Chapitre 97 - En entrant dans une ville ou un village
-- Chapitre 98 - En entrant au marché
-- Chapitre 99 - Lorsque la monture trébuche
-- Chapitre 100 - Du voyageur au résident
-- Chapitre 101 - Du résident au voyageur
-- Chapitre 102 - Proclamer la grandeur et la gloire d'Allah au cours du voyage
-- Chapitre 103 - Du voyageur aux dernières heures de la nuit
-- Chapitre 104 - Lorsque l'on campe en plein air
-- Chapitre 105 - Du retour du voyage
-- Chapitre 106 - Que dire lorsque l'on reçoit une bonne ou une mauvaise nouvelle
-- Chapitre 107 - Le mérite de la prière sur le Prophète (saws)
-- Chapitre 108 - Le mérite de saluer
-- Chapitre 109 - La manière de rendre le salut au mécréant
-- Chapitre 110 - En entendant le chant du coq et le braiment de l'âne
-- Chapitre 111 - En entendant les aboiements des chiens la nuit
-- Chapitre 112 - En faveur de ceux que l'on a insultés
-- Chapitre 113 - Ce que l'on doit dire lorsqu'on vante les mérites de quelqu'un
-- Chapitre 114 - Ce que doit dire celui qui reçoit des éloges
-- Chapitre 115 - La Talbiya pour celui qui effectue le Haj et la 'Omra
-- Chapitre 116 - Le Takbîr en passant devant la pierre noire
-- Chapitre 117 - Entre le coin 'yéménite' et la pierre noire
-- Chapitre 118 - En montant As-Safâ et Al-Marwa et l'invocation à y dire
-- Chapitre 119 - Du jour de 'Arafat
-- Chapitre 120 - Le rappel à Muzdalifa
-- Chapitre 121 - Dire : 'Allah est le plus Grand' en lapidant les stèles
-- Chapitre 122 - Lors de l'étonnement et de l'admiration
-- Chapitre 123 - Lorsque l'on reçoit une bonne nouvelle
-- Chapitre 124 - Que doit dire celui qui ressent une douleur dans son corps
-- Chapitre 125 - Contre le mauvais oeil
-- Chapitre 126 - En cas de frayeur
-- Chapitre 127 - En égorgeant une bête
-- Chapitre 128 - Pour écarter la ruse et le complot des diables rebelles
-- Chapitre 129 - La demande d'absolution et le repentir
-- Chapitre 130 - Les mérites de dire 'gloire à Allah, louange à Allah, il n'y a de divinité qu'Allah, Allah est le plus Grand'
-- Chapitre 131 - La manière dont le Prophète (saws) glorifiait Allah (at-Tasbîh)
-- Chapitre 132 - Parmi les règles générales et bénéfiques
*/
}
