package com.alpha.commun;

import java.io.BufferedReader;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.util.ArrayList;
import java.util.List;

import android.content.Context;

public class HadithList
{

private static HadithList instance;
private List<String> hadithList;
private List<String> refList;
private static int i = -1 ;	
	
public static HadithList getInstance(Context context) {
	if(instance == null)
		instance = new HadithList(context);
	return instance;
}
	
private HadithList(Context context) {
	this.hadithList = new ArrayList<String>();
	this.refList = new ArrayList<String>();
	
	try{
		InputStream is = context.getAssets().open("doc/hadith.slc");
        if (is != null)            	
      	  	{
      	    BufferedReader bread = new BufferedReader(new InputStreamReader(is));
      	    while (bread.ready()) {
      	        String s = bread.readLine();
      	        if (s.length()>1)
	      	    {
	      	        if (s.startsWith("_"))
	      	        	{
	      	        		this.hadithList.add(s.substring(1));
	      	        	} else if (s.startsWith("#"))
	      	        	{
	      	        		this.refList.add(s.substring(1));      	        		
	      	        	}
      	        }
      	    }
      	  		is.close(); 
      	  	}
	}catch (Exception ex)
	{
		
		
	}


}	
	

public String getHadith(int ref)
{
if (ref<0)
	{
		ref = (int)(Math.random()*hadithList.size());
	}
i = ref;
return (i<hadithList.size())? hadithList.get(i) : "";
}


public String getSourceHadith()
{
return (i<refList.size())? refList.get(i) : "" ;
}

private static int[][] rabbana=
{
{2,127,2},{2,201,1},{2,250,1},{2,285,1},{2,286,1},{3,8,1},{3,16,1},{3,38,1},{3,53,1},{3,147,1},{3,191,3},{3,194,1},{4,75,1},
{5,83,1},{7,23,1},{7,47,1},{7,89,1},{7,126,1},{7,151,1},{9,129,1},{10,85,2},{11,47,1},{14,35,1},{14,40,1},{14,41,1},
{17,80,1},{18,10,1},{20,25,4},{20,114,1},{21,89,1},{23,93,2},{23,97,2},{23,109,1},{23,118,1},{25,65,2},{25,74,1},
{26,83,3},{27,19,1},{28,16,1},{28,17,1},{28,21,1},{28,24,1},{29,30,1},{37,100,1},{40,7,3},{44,12,1},{46,15,1},
{71,28,1},{59,10,1},{60,4,1},{60,5,1},{66,8,1}
};

/*
private static String[] hadith={
"Je vous laisse deux choses : aussi longtemps que vous vous y conformerez, vous ne vous égarerez jamais du droit chemin; il s’agit du Livre d’Allah et de la Sunna de Son Messager.",
"Celui qui est satisfait d’Allah comme Seigneur, de l’Islam comme religion et de Mohammad e comme Messager, a goûté à la douceur de la Foi.",
"Les croyants qui ont la foi la plus parfaite sont ceux qui ont les meilleures manières.",
"Ce monde est une prison pour le croyant et un paradis pour l’incroyant.",
"Quiconque imite (les pratiques religieuses) d’un peuple en fait partie.",
"Le musulman qui se mêle aux gens et supporte leurs torts avec patience est meilleur que celui qui ne se mêle pas à eux et qui n’est pas patient.",
"Béni soit celui qui a été guidé dans l’Islam et dont les moyens de subsistance sont juste suffisants, mais qui sait s’en contenter.",
"Tous mes fidèles entreront au paradis sauf ceux qui le refusent. On interrogea le Messager de Dieu e : Et qui refuse d’y aller? Il répondit : Ceux qui m’obéissent entreront au paradis mais ceux qui me désobéissent l’ont refusé.",
"Celui qui consomme ce qui est licite, qui met une sounnate en pratique et qui ne nuit point à autrui, est sûr d’entrer au paradis. Un homme s’exclama : O Messager d’Allah ! De nombreuses personnes agissent comme cela de nos jours! Le Prophète répondit : Et ce sera ainsi dans les générations à venir.",
"Le contentement de Dieu se trouve dans le contentement du père et Son mécontentement dans le mécontentement du père.",
"Un homme demanda : O Messager d’Allah ! Quels sont les droits des parents sur leurs enfants? Il répliqua : Ils sont votre paradis et votre enfer.",
"Aucun père ne peut offrir de meilleur cadeau à son fils que les bonnes manières.",
"J’ai dix enfants et je n’en ai jamais embrassé aucun. Le Prophète d’Allah regarda dans sa direction et lui dit : On ne fera pas preuve de bonté envers celui qui n’est pas bon.",
"Le meilleur d’entre vous est celui qui se conduit le mieux envers sa famille et je suis le meilleur envers la mienne.",
"Chaque fois qu’un musulman dépense quelque chose pour sa famille, en espérant là une récompense (de la part de Dieu), cela lui est compté comme acte de charité.",
"Qu’aucun croyant ne déteste une croyante. S’il hait un de ses traits de caractère, il devrait pouvoir en apprécier un autre.",
"Toute femme qui meurt alors que son mari est content d’elle entrera au paradis.",
"Le plus parfait des croyants est celui qui a la meilleure conduite. Les meilleurs d’entre vous sont ceux qui sont les meilleurs avec leurs femmes.",
"Allah vous a confié vos frères; quiconque a la responsabilité de son frère doit le nourrir de ce qu’il mange et le vêtir de ce qu’il porte. Il ne doit pas le charger d’un travail dont il ne pourra venir à bout, sinon, il devra l’aider.",
"O Prophète d’Allah ! Quel est le meilleur acte de charité? Il répondit : C’est celui que l’on destine à un nécessiteux. Et commencez par la personne avec qui vous avez des liens de parenté.",
"Si un jeune homme honore un vieil homme en raison de son âge, Allah lui enverra quelqu’un qui le traitera de la même façon dans ses vieux jours.",
"Abou Omamah (R.A) rapporte qu'un jour le Messager d’Allah vint vers eux, en s’appuyant sur un bâton. Nous nous mîmes debout pour l’accueillir. Alors il déclara : Ne vous levez pas comme le font les étrangers, certains d’entre eux marquant du respect à l’égard de certains autres.",
"Quand un homme respectable d’une tribu vient vers vous, honorez-le.",
"Celui qui cause du tort à son voisin n’entrera pas au paradis.",
"Quand vous cuisinez un plat (de viande), ajoutez-y de l’eau et offrez-en à vos voisins.",
"Chaque fois que l’un d’entre nous se plaignait de maladie au Prophète de Dieu, il avait l’habitude de passer sa main droite sur lui et de dire :O Seigneur des hommes ! Débarrasse- le de son mal et guéris-le. ô Guérisseur ! Il n’est nulle guérison en dehors de la tienne - qui ne laisse aucun mal -.",
"Le Messager d’Allah me rendit visite alors que j'avais les yeux malades.",
"Quand vous rendez visite à un malade, chassez son angoisse à l’égard de la mort ; ça ne pourra rien empêcher mais ça réconfortera son âme.",
"Anas (R. A) rapporte que le Prophète d’Allah avait l’habitude de rendre visite aux malades au bout de trois jours seulement.",
"Quand vous rendez visite à un malade, demandez-lui de prier pour vous ; sa prière est semblable à celle des anges.",
"Vous verrez les croyants être bons les uns envers les autres, se manifestant de l’amour et de la sympathie, comme s’ils ne formaient qu'un seul corps. Lorsqu’un membre se plaint, le corps tout entier lui répond par la fièvre et la veille.",
"Le croyant est pour son semblable comme une construction dont les parties se soutiennent mutuellement. Le Messager de Dieu illustra ses paroles en entrelaçant ses doigts.",
"Vous n’entrerez au paradis que si vous croyez ; et vous ne croirez que lorsque vous vous aimerez les uns les autres.Puis-je vous indiquer une chose qui vous fera vous aimer? Saluez - vous. ( Adressez-vous le Salam. ).",
"Il n’est pas permis à un musulman de rompre toute relation avec son frère plus de trois jours consécutifs. Celui qui agit ainsi et meurt dans cet état entrera dans le feu.",
"Maudit soit celui qui injurie un croyant et le trompe.",
"Ne te réjouis pas devant les malheurs de ton frère, de crainte qu’Allah n’ait pitié de lui et ne t’éprouve à ton tour.",
"Les droits d’un musulman envers son frère sont au nombre de cinq :- Lui rendre son salut.- Lui rendre visite en cas de maladie.- Suivre son cortège funèbre.- Répondre à son invitation.- Lui réciter la supplique suivante quand il éternue:\"Que Dieu te soit Miséricordieux.\"",
"Quand un musulman rend visite à son frère malade, il continue très certainement à cueillir les fruits du paradis jusqu’à son retour (chez lui).",
"Quiconque accomplit ses ablutions correctement, puis rend visite à son frère musulman malade,dans l’espoir d’obtenir une récompense s’éloigne du feu de l’enfer d’une distance de soixante années.",
"Mangez ensemble et non séparément, ainsi votre repas sera béni.",
"Allah pardonne les péchés mineurs du musulman qui souffre d’un mal quelconque, qu’il s’agisse d’une affection durable, d’une inquiétude, d’un chagrin, d’un tort, d’un désastre ou même d’une épine qui le pique.",
"Ja’ber (R.A) rapporte que le Prophète d’Allah se rendit auprès de la mère de Saeb ( R.A ) et lui demanda :-Pourquoi trembles-tu?  -C’est la fièvre, répondit - elle, qu’Allah la maudisse. Le Messager de Dieu déclara alors : Ne dénigrez pas la fièvre, car elle éloigne les péchés des enfants d’Adam (A.S) de la même façon que le soufflet élimine les impuretés du fer.",
"La mort, en terre étrangère, est un martyr.",
"Allah n’est pas bon avec celui qui n’est pas bon envers son prochain.",
"Une femme fut punie pour avoir enfermé un chat qui finit par mourir de faim. Elle ne lui donna rien à manger et ne le libéra même pas pour qu’il puisse se nourrir de quelques vers de terre.",
"Celui qui est dépourvu de bonté est dépourvu du bien.",
"Celui qui s’approprie injustement un empan de terre se le verra suspendu autour du cou, le jour du Jugement, son étendue prise dans les sept terres.",
"Ne braquez pas de lance (d’arme) sur autrui de crainte que le démon ne s’en empare et ne vous précipite dans le feu (en vous poussant à commettre un crime ).",
"Quand un homme meurt, toutes ses actions deviennent sans effet à l’exception de trois d’entre elles :- Un acte de charité perpétuel.- La connaissance qu’il a dispensée aux autres.- Un fils vertueux priant pour lui.",
"Celui qui part à la recherche de la connaissance est dans le chemin d’Allah jusqu’à son retour.",
"Soyez prudent lorsque vous rapportez mes Traditions. Celui qui m' attribue un mensonge trouvera refuge dans le feu.",
"Apprenez les doctrines obligatoires et le Qouran puis enseignez - les aux gens, car je suis mortel.",
"Le Prophète d’Allah a dit : Dieu élèvera au rang de théologien quiconque préserve quarante traditions pour mon peuple. De plus, je serai son intercesseur le jour du jugement et je témoignerai en sa faveur.",
"Celui qui interprète le Qouran selon son bon plaisir trouvera refuge dans le feu. Et dans un autre hadice : Celui qui interprète le Qouran sans connaissance trouvera refuge dans le feu.",
"Celui qui interprète le Qouran à sa guise, a commis un péché même si son interprétation est juste.",
"Quiconque guide vers le bien aura la récompense de celui qui l’a accompli.",
"Si un homme commet un péché au sein de son peuple, et que ses membres ont le pouvoir de l’en empêcher et ne le font pas, alors, à cause de lui, Allah leur enverra un châtiment avant qu’ils ne meurent.",
"Celui qui m’est le plus cher est celui qui a la meilleure conduite.",
"Le meilleur d’entre vous est celui qui a la meilleure conduite.",
"J'ai été envoyé pour parfaire les bonnes manières.",
"Celui qui renonce au mensonge aura un château dans un coin du paradis ; celui qui renonce à la dispute alors qu’il est dans son droit, aura un château au milieu du paradis ; et celui qui a une bonne conduite en aura un, construit dans sa partie la plus élevée.",
"O Allah ! Tu m’as accordé une bonne constitution, alors accorde - moi une bonne conduite.",
"Les portes du paradis sont à l' ombre des épées.",
"Celui qui prend sa corde et s’en revient avec une charge de bois sur le dos, afin de la vendre, est meilleur que celui qui mendie auprès des hommes, que ceux-ci lui fassent l’aumône ou la lui refusent. Ainsi Allah préserve son honneur.",
"Nul n’a jamais mangé de meilleure nourriture que celle qu’il a obtenue du travail de ses mains. En outre, Dawood (A.S), le Prophète d’Allah, se nourrissait du fruit de son travail.",
"Le plus pur de ce que vous consommez provient de votre propre salaire.",
"Le jour du Jugement, nul ne pourra s’éloigner avant d’avoir rendu des comptes sur quatre faits :- sa vie : comment l’a-t-il passée? - la connaissance qu’il a reçue : à quelles fins l’a - t - il utilisée? - ses biens : comment les a - t - il acquis et dépensés? - son corps : qu’en a t - il fait? .",
"Évitez les sept péchés capitaux :\"Les compagnons demandèrent : quels sont-ils, ô Messager d’Allah? Ce dernier répondit : - Associer quelqu’un à Dieu.- La magie.- Le meurtre.- L’usure.- S’approprier les biens des orphelins.- Tourner le dos au djihad.- Accuser à tort les femmes chastes et innocentes.\"",
"Le commerçant honnête et digne de confiance se retrouvera avec les prophètes, les martyrs et les hommes pieux (le jour du jugement).",
"Si un oiseau, un animal quelconque ou un homme mange des fruits d’un arbre planté par un musulman ou se nourrit de la récolte d’un champ qu’il a semé, ce sera pour lui un acte de charité.",
"Abou Horeira (R. A) a déclaré : O Prophète d’Allah ! Je suis à toi. Raçouloullah, continue Abou Horeira ( R. A ), prit ma main et m’énuméra les cinq conseils suivants :- Évite ce qui est illicite et tu prieras plus que les autres.- Sois satisfait de ce qu’Allah t’a accordé et tu n’auras jamais l'impression qu’il te manque quelque chose.- Sois bon envers tes voisins et tu deviendras un vrai croyant.- Choisis pour les autres ce que tu choisis pour toi et tu seras un parfait croyant.- Ne ris pas trop car le rire fait mourir le coeur.",
"Prenez les six engagements suivants et je prendrai la responsabilité de vous faire entrer au paradis.Dites toujours la vérité ; tenez vos promesses ; rendez ce qui vous a été confié en bon état ; cachez vos parties intimes ;baissez les yeux ; retenez vos mains ( de la tyrannie et des mauvaises actions ).",
"Celui dont la nourriture est licite, qui applique la sounna et qui ne cause aucun tort à autrui entrera au paradis.",
"Quiconque tue un moineau ou une créature plus petite sans raison valable aura des comptes à rendre à son sujet.",
"Hazrat Aicha ( R. A ) rapporte ceci : Je montais un chameau indocile et le fis tourner plutôt rudement Raçouloullah me dit alors : Il t’appartient de traiter les animaux avec douceur.",
"Les gens qui utilisent n’importe quelle créature vivante à des fins sportives sont condamnés.",
"Le Prophète a interdit tout sport sanglant, comme en pratiquaient les bédouins.",
"N' utilisez pas les créatures vivantes comme cibles.",
"Ceux qui utilisent les créatures vivantes comme cibles sont condamnés.",
"Le messager d’Allah a interdit qu’on incite les animaux à se battre entre eux.",
"Raçouloullah raconta à ses compagnons qu’un esclave fut béni par Allah pour avoir sauvé la vie d’un chien en lui donnant de l’eau à boire, afin d’apaiser sa soif.",
"On rapporte que le Prophète d’Allah a dit qu’il était interdit de faire attendre 1’animal qu’on doit abattre.",
"Le Prophète d’Allah a dit :- Regarder une femme étrangère, c'est commettre l’adultère avec les yeux.- Écouter des mots susceptibles de faire naître la passion ou le désir, c'est commettre l’adultère avec les oreilles.- Converser avec une femme étrangère et en tirer du plaisir, c'est commettre 1' adultère avec la langue.- Toucher une femme étrangère, c'est commettre l'adultère avec les mains.- Aller à sa rencontre, C'est commettre l’adultère avec les pieds.- Le coeur désire avec passion ; les organes sexuels répondent à son appel ou s’y refusent.",
"Un sahabi interrogea le Prophète au sujet du beau -frère (rencontrant en privé la femme de son frère).Raçouloullah répliqua :Le beau-frère est comme la mort.",
"Le Messager d’Allah a dit : Nul ne doit rencontrer de femme étrangère en dehors de la présence de l’un de se:\"mahram\".",
"Maudit soit celui qui commet l’acte du peuple de Lot (A.S).",
"Allah Ta’ala n'aura pas de pitié pour celui qui pratique la sodomie avec sa femme.",
"Ne regardez pas un adolescent imberbe.",
"Méfiez vous des jeunes hommes imberbes, car ils représentent une source de mal bien plus grande que les jeunes filles.",
"En vérité, il y a ce qui est clairement licite et ce qui est clairement illicite ; entre les deux, se trouvent les cas douteux. Peu de gens en ont connaissance ; mais celui qui s’en préserve protège sa foi et son honneur. Par contre, celui qui y tombe, tombe dans l’illicite, tel un berger faisant paître son troupeau autour d'un pâturage interdit - mais vraisemblablement fait pour cela. Chaque roi possède un endroit protégé (tel ce pâturage interdit). Méfiez-vous; les lieux protégés d’Allah sont les choses qu’II a déclarées illicites.",
"Évitez ce que je vous ai interdit et persévérez dans ce que je vous ai enseigné ; en vérité, ceux qui vous ont précédés ont péri pour avoir posé trop de questions ( d’inutiles questions ) et pour s’être querellés avec leurs prophètes ( A. S ).",
"Une partie de la beauté de l’Islam d’un homme réside dans le fait de laisser de côté ce qui ne le concerne pas.",
"Aucun d’entre vous n’est un vrai croyant tant qu’il n’aime pas pour son frère ce qu’il aime pour lui - même.",
"Celui qui croit en Dieu et au Jour du Jugement, doit parler intelligemment ou se taire. De même, celui qui croit en Dieu et au jour du Jugement, doit honorer ses voisins et ses invités.",
"Ne vous laissez pas emporter par la colère. L’homme questionna à nouveau le Messager d’Allah qui lui donna le même conseil à sept reprises : Ne vous laissez pas emporter par la colère.",
"En vérité, Allah a prescrit la douceur pour toute chose. Alors, quand vous tuez une bête, faites-le avec bonté ; vous devez aiguiser votre couteau et donner à l’animal abattu le temps de mourir.",
"Craignez Allah en tous lieux. Faites suivre tout péché d’une bonne action qui l’effacera. Enfin, comportez-vous bien avec les gens.",
"En vérité, chaque tasbih est un acte de charité ;chaque Tahmid est un acte de charité tout comme le fait de commander le bien et d’avoir des rapports (avec vos épouses) Surpris, ils demandèrent: O Prophète d’Allah ! Est-il possible, qu’en satisfaisant notre passion, nous soyons ainsi récompensés? Raçouloullah répondit : Réfléchissez. Si vous cherchez à assouvir votre désir par des moyens illicites, n’est-ce pas là un péché? Eh bien, de la même façon, il y a une récompense pour celui qui le fait licitement.",
"Qu’il n'y ait ni tort, ni malfaisance.",
"Si les revendications des gens sont acceptées, certains réclameront le bien ou le sang d’autrui. Par conséquent, le plaignant doit apporter des preuves et l’accusé ( celui qui rejette l’accusation ) prêter serment.",
"Celui d’entre vous qui voit une chose répréhensible doit l’empêcher avec sa main; s’il ne le peut, avec sa langue, et, si cela ne lui est toujours pas possible, que ce soit en son for intérieur. C' est là le minimum exigé par la foi.",
"Soyez en ce monde, comme un étranger ou un passant.",
"Aucun d’entre vous ne peut être un bon croyant si ses désirs ne sont pas contrôlés par ce que je vous ai apporté.",
"N’insultez pas les morts sinon vous blesseriez les vivants.",
"Tout divertissement n’est que pure vanité ;aucun n’est digne de louanges, à l’exception de trois d’entre eux, à savoir: dresser un cheval, plaisanter avec sa femme et tirer à l’arc. Ceux-ci sont certainement bons.",
"Quand l’un de vous est en colère, s’il est debout, faites-le s'asseoir ; et si sa colère s’apaise, c’est bien.Autrement, faites - le s'allonger.",
" Un moineau tué sans raison se plaindra avec véhémence auprès d’Allah, en criant : O mon Seigneur ! Tel homme m’a tué pour rien ; il m’a tué sans raison valable.",
"Il existe parmi nous, des gens qui consultent les devins. Raçouloullah a dit : Alors n’allez pas chez eux.",
"Je me porte garant de l’entrée au paradis de celui qui me certifie qu'il ne mendiera jamais auprès des gens.",
"Raçouloullah a maudit celui qui verse ou qui reçoit des pots - de - vin (qui a recours à la corruption) lorsqu’il s’agit de traiter une affaire.",
"Ne montre pas ta joie devant les malheurs de ton frère; Allah pourrait faire preuve de miséricorde à son égard et t’éprouver à ton tour.",
"Chaque bonne parole est un acte de charité.",
"Ordonner ce qui est raisonnable est un acte de charité; interdire ce qui est répréhensible est aussi un acte de charité -",
"Qu’un musulman plante un arbre ou sème un champ, que les oiseaux, les hommes ou les bêtes s’en nourrissent, alors ceci est un acte de charité.",
"Un homme demanda : O Raçouloullah ! Je possède un dinar.\nLe Messager de Dieu dit : Alors garde-le pour toi.\nL’homme ajouta qu’il en avait un second.\nRaçouloullah dit encore : Garde - le pour ton enfant.\n-J’en possède un autre, avoua l’homme.\n-Alors accorde-le à ta femme, rétorqua le Prophète.\n-J’en ai encore un, dit à nouveau l’homme.\n-Garde-le pour ceux qui dépendent de toi, lui recommanda Raçouloullah.\n-J’en ai un autre, déclara enfin l’homme.\n-Alors, dit le Prophète, accorde-le à celui qui le mérite.",
"La charité apaise la colère d'Allah.",
"Qu’un homme donne un dirham en charité, de son vivant, vaut mieux pour lui que s’il en distribuait mille à sa mort.",
"La propreté est la moitié de la foi.",
"Il vaut mieux rester seul que d’avoir un mauvais compagnon; mais un bon compagnon est préférable à la solitude. De même, il vaut mieux ordonner le bien que garder le silence ; cependant, le silence est préférable à l’incitation au mal.",
"Celui qui ressent de la compassion pour la mère d’un enfant mort sera vêtu d’un habit au paradis.",
"Béni soit celui qui a été guidé dans l’Islam et qui n’a d’autre moyen de subsistance que son pain quotidien, mais qui sait s’en contenter.",
"Quand l’un d’entre vous en voit un autre qui lui est supérieur du fait de sa fortune, qu’il regarde celui qui a été moins favorisé que lui. Il est plus juste que vous ne dédaigniez point les faveurs que vous a accordées Allah.",
"Celui qui maudit quelque chose qui ne le mérite pas risque de voir cette malédiction se retourner contre lui.",
"Tous les péchés d’un martyr sont pardonnés à l’exception de ses dettes.",
"Le riche qui remet à plus tard le paiement de ses dettes, commet une mauvaise action.",
"Quiconque s’empare de la fortune des hommes dans le but de la faire fructifier, Allah lui rendra la pareille ; mais Allah ruinera quiconque agit ainsi dans l’intention de la dilapider.",
"Je dis: O Prophète d’Allah ! J’ai tellement de cheveux sur la tête ! Dois - je les peigner? Le Prophète d’Allah répondit : Oui, et ce ne sera que justice (envers eux).",
"Celui qui a une chevelure, qu’il soit juste envers elle.",
"Prendre le temps de réfléchir appartient à Allah, la hâte à Satan.",
"Parmi les choses permises, le divorce est ce qu’Allah déteste le plus.",
"La femme qui demande le divorce à son époux, sans y être contrainte ( par de mauvais traitements ou autre... ) ne sentira pas le parfum du paradis.",
"L’ivresse est la somme de tous les péchés ( et la mère de tous les vices ).",
"Les liqueurs enivrantes sont interdites.",
"Nul cadeau qu’un parent peut faire à son enfant ne vaut une bonne éducation.",
"Ne me louez point comme les chrétiens louent le fils de Marie, car, en vérité, je suis un serviteur d’Allah; parlez donc de moi comme d’un serviteur de Dieu et Son envoyé.",
" Le meilleur de la foi est d’affirmer qu’il n’y a pas d’autre Dieu que Dieu ; et son minimum, de débarrasser la voie publique des choses gênantes.",
"La foi est une barrière contre tout acte de violence injustifié; qu'aucun croyant n' en commette.",
"Je demandai : Qu' est - ce que l'Islam? L’Envoyé de Dieu me répondit : Pureté de parole et hospitalité.Je demandai encore : Et qu’est - ce - que la foi? Il me dit : Patience et oeuvres de bienfaisance.Je continuai : Qui est le meilleur dans l’Islam? L’Envoyé de Dieu déclara : Celui qui ne cause aucun tort à autrui, avec sa langue et sa main :\"J' ajoutai : Et quel est le meilleur de la foi? Il me répondit : Une bonne nature.Je demandai à nouveau : 0 Prophète ! Quel est le meilleur Djihad? Raçouloullah dit : Le fait de fuir ce qu'Allah déteste.Je dis encore : Et la meilleure prière? Il affirma : une prière continuelle.\"",
"Celui qui élève trois filles ou trois soeurs, ou encore deux filles ou deux soeurs, les éduque bien, les traite avec bonté et les donne en mariage, obtiendra le paradis.",
"Quand les fils d’Israël tombèrent dans le péché, leurs savants les en empêchèrent, mais ils ne cessèrent point; ces savants finirent par s’asseoir avec eux,par manger et boire en leur compagnie. Alors Allah frappa leur coeur - les uns après les autres - et les maudit par l’intermédiaire de Dawood ( A. S ).Par Celui qui détient ma vie entre Ses mains ! Tant que vous n’avez pas inspiré aux hommes l’amour de la Vérité, vous n’avez rien fait.",
"Les peuples qui vous ont précédés n’ont péri que parce que lorsqu’un homme de haute naissance, parmi eux, volait, ils laissaient sa faute impunie ; tandis que lorsqu’un faible agissait de même, ils le châtiaient. Par Dieu ! Si Fatima (R), la fille du Prophète, avait volé, je lui aurais certainement coupé la main.",
"Il n’est pas autorisé de faire un présent ou une donation puis de se rétracter, à moins qu’il ne s’agisse du don d’un père ou d’une mère à son enfant. Celui qui reprend ce qu’il a donné,est comme un chien qui ravale son propre vomi.",
"La meilleure parole est d’affirmer :\" Il n’y a pas d’autre Dieu que Dieu.\"",
"Allah n'accepte que ce qui est bon.",
"Nourris l’affamé, visite le malade et libère le captif.",
"Celui qui n’est pas reconnaissant envers les hommes, n’est pas reconnaissant envers Allah.",
"Visitez les tombeaux ;en vérité, cela vous rendra indifférent à ce bas - monde et vous fera penser à l’au - delà.",
"Faites attention ! Ceux qui vous ont précédés ont utilisé les tombes de leurs Prophètes et de leurs hommes pieux comme lieux de culte. Prenez garde ! N’utilisez pas vos tombes aux mêmes fins ; je vous l’interdis.",
"Ne vous asseyez pas sur les tombes et ne priez pas en vous tournant dans leur direction.",
"Le meilleur des djihads est de proclamer la vérité à la face d’une autorité tyrannique.",
"Celui qui renonce à de beaux vêtements par humilité, alors qu’il a les moyens d’en porter, sera appelé par Allah le Jour de la résurrection, à la tête de la création et sera grandement récompensé.",
"Il existe trois caractéristiques chez l’hypocrite, alors même qu’il jeûne, prie et pense qu’il est musulman. Il ment quand il parle, il ne tient pas ses promesses et trahit ceux qui lui font confiance.",
"Quatre qualités révèlent le parfait hypocrite ; quiconque en possède une, garde en lui une part d’hypocrisie, et ce, jusqu’à ce qu’il s’en soit débarrassé ; à savoir:- Il trahit quand on lui fait confiance.- Il ment quand il parle.- Il met dans l’embarras celui qui compte sur lui.- Il fait preuve de méchanceté lors de litiges.",
"Chaque religion met l’accent sur une vertu particulière et la vertu de l’islam, c’est la modestie.",
"C’est une des beautés de l’islam le fait qu’un homme ne se mêle pas de ce qui ne le regarde pas.",
"Ne laissez pas celui qui est en colère intervenir (juger) entre deux individus, lors d’un procès (ou d’une requête) qui les oppose.",
"Allah facilitera la route qui mène au paradis à celui qui s'engage sur le chemin de la connaissance.",
"Celui qui part à la recherche de la connaissance s’engage pour la cause de Dieu, et ce, jusqu’à ce qu’il rentre chez lui.",
"Apprenez vos devoirs et enseignez - les aux autres.",
"Puis - je vous enseigner une chose qui, lorsque vous la mettrez en pratique, vous fera vous aimer?  Eh bien, saluez vous.",
"Le jour de la Résurrection, l’homme sera en compagnie de ceux qu’il aime.",
"Un homme vint et demanda :\"0 ! prophète d’Allah ! Que pensez vous de celui qui aime une personne avec laquelle il n’a aucun lien de parenté?  Le Prophète (e) répondit : L'homme sera avec ceux qu’il aime.\"",
"Quand le Prophète (e) m’envoya au Yémen comme gouverneur, il me dit: Prends garde de ne point tomber dans le luxe, car les serviteurs d’Allah ne mènent pas une vie luxueuse.",
"Quand un serviteur d’Allah ment, les anges (qui l’accompagnent) s’éloignent de lui d’une distance d’un mile (1,609 m), à cause des troubles intérieurs qui en découlent.",
"O Prophète d’Allah ! Quel est la meilleure chose qui puisse être donnée à un homme? - Les bonnes manières, dit Raçouloullah (e) ",
"Qu’aucun d’entre vous ne fasse se lever celui qui est assis dans le but de lui prendre sa place. Par contre,faites de la place pour tous, de sorte qu’Allah vous en fasse.",
"Quand il y a trois hommes, que deux d’entre eux ne se lancent pas dans une conversation sans y faire participer le troisième ; cela pourrait le chagriner.",
"On épouse une femme pour quatre raisons pour sa richesse, son origine, sa beauté et sa Religion ; en ce qui vous concerne, choisissez une épouse pour sa piété ( son dîne) ; si vous l’épousez pour une autre raison, vos mains en seront souillées.",
"Celui qui prescrit un médicament sans avoir de connaissances médicales, sera tenu pour responsable du résultat.",
"En vérité, le jour de la résurrection, les commerçants se retrouveront avec les pécheurs, à l’exception de ceux qui ont craint Allah,ont fait preuve de bonté et ont dit la vérité.",
"Un contrat injuste fait s’écouler la marchandise mais empêche les bénéfices.",
"Allah n’est pas compatissant avec celui qui ne fait pas preuve de compassion envers ses semblables.",
"Il n’est pas des nôtres, celui qui n’est pas tendre envers nos jeunes, ne respecte pas nos vieux, ne prescrit: pas le bien et n’interdit pas le mal.",
"Celui qui prescrit le bien est comme celui qui l’accomplit.",
"Celui qui montre la voie du bien a la même récompense que celui qui le fait.",
"Mangez, donnez la charité et habillez-vous sans extravagance ni vanité.",
"En vérité, la modestie n’apporte que des bienfaits.",
"En vérité, la modestie et tout ce qu’elle comporte, est bonne.",
"En vérité, la modestie et la foi dépendent l’une de l’autre; quand l’une d’entre elles disparaît, l’autre finit aussi par s’en aller.",
"Celui qui détient un monopole est un pécheur.",
"Raçouloullah a maudit les pleureurs professionnels.",
"Il n’est pas des nôtres, celui qui se gifle, qui déchire ses vêtements et se lamente comme au temps de l’ignorance.",
"En voyage, Raçouloullah fermait la marche, prenant soin des faibles, les asseyant derrière lui et il priait aussi pour eux.",
"Le croyant n’est ni celui qui rejette ou maudit les autres, ni celui qui accomplit de mauvaises actions, ni un impertinent.",
"N’est pas croyant celui qui mange tout son soûl, tandis que son voisin reste affamé de son côté.",
"Il n’est pas permis à un musulman d’effrayer un autre musulman.",
"Le musulman qui se mêle aux gens et supporte patiemment les torts qu’ils peuvent lui causer est meilleur que celui qui ne se mêle pas aux autres et ne supporte pas leurs torts avec patience.",
"Par Dieu ! Il ne croit pas, répéta à trois reprises Raçouloullah.- Et qui ne croit pas?  lui demanda - t - on.Il répondit : Celui dont les voisins redoutent les méchancetés.",
"Celui qui prête un faux serment trouvera sa place en enfer.",
"Point d’obéissance à la créature quand il y a désobéissance au Créateur.",
"L'mujahid' est celui qui accomplit l'djihad' contre lui-même, en obéissant à Allah ; l'mujahir' est celui qui s’abstient de tout crime et de tout péché.",
"L 'mujahi' est celui qui s’abstient de ce qu’Allah a interdit.",
"Allah fera en sorte que soit honoré dans ses vieux jours, le jeune homme qui respecte le vieillard à cause de son âge.",
"Considérez cinq choses avant cinq autres :- votre jeunesse avant que vous ne deveniez vieux ;- votre santé avant que vous ne tombiez malade- votre richesse avant que vous ne deveniez pauvre- votre temps libre avant que vous ne soyez affairés ;- et enfin, votre vie avant que vous ne mourriez.",
" Un homme se plaignit au Prophète, de sa propre dureté de coeur. Celui - ci lui dit : Passe ta main sur la tête des orphelins et nourris les pauvres.",
"Celui qui pourvoit aux besoins de la veuve et de l’orphelin, est semblable à celui qui combat dans le chemin d'Allah, ou qui prie toute la nuit, ou encore, qui jeûne tout le jour.",
"Le pire des festins est celui du mariage auquel seuls les riches assistent, tandis que les pauvres n’y sont point conviés.",
"Que chacun d’entre vous demande à son Seigneur tout ce qu’il désire.",
"La clé du paradis est la prière, et la clé de la prière est la pureté.",
"Trois prières sont exaucées - il n’y a aucun doute à ce sujet: celle des parents, celle du voyageur et enfin, celle de l’opprimé.",
"Ne demandez rien,'baddoahs' ) à Dieu contre vous - même, contre vos enfant, vos serviteurs ou vos biens.",
"Priez debout et si vous ne le pouvez, faites-le assis; si vous n’en êtes toujours pas capable, alors, priez allongés sur le côté.",
"Raçouloullah avait l’habitude de recevoir des cadeaux et d' en envoyer en retour.",
"Faites - vous des cadeaux car, en vérité, ils éloignent la rancune du coeur ; et que nul ne méprise le cadeau de son voisin, aussi petit soit - il.",
"Allah habillera de disgrâce celui qui porte des vêtements par ostentation.",
"Celui qui lit la lettre de son frère sans sa permission a le regard tourné vers le feu ( dans lequel il sera précipité ).",
"Le plus détestable des hommes aux Yeux d’Allah est le plus querelleur.",
"Aucune nation ne s’est égarée du droit chemin, après avoir été bien guidée, sauf celles au sein desquelles il y avait des dissensions.",
"Apprenez le Qouran et enseignez-le aux autres ; en vérité, je ne suis qu’un homme qui mourra un jour.",
"Raçouloullah aime que l’on soit régulier dans ses (bonnes) actions, aussi minimes soient - elles.",
"Celui qui se nourrit licitement, qui agit conformément à ma Sounna et qui ne nuit point à autrui entrera au paradis.",
"Le plus digne des hommes est celui qui salue le premier.",
"Un homme doit saluer son épouse et ses enfants, quand il rentre chez lu.",
"Le cavalier commence par saluer le piéton; le piéton salue le premier celui qui est assis et le plus petit groupe (de personnes) salue le plus important.",
"Raçouloullah me dit : O mon enfant! Quand tu rends visite à ta famille, salue-la ; ce sera une bénédiction pour toi et pour ceux de ta maison.",
"Quand vous rentrez chez vous, saluez les gens qui s’y trouvent et quand vous sortez, prenez congé d’eux en les saluant.",
"Comment obtenir le salut?  demanda-t-on au prophète Il répondit : Retenez votre langue, restez chez vous et repentez - vous de vos péchés ( en pleurant ).",
"O Abou - Dharr ! Il n’existe pas de meilleure ( preuve de ) sagesse que l’organisation, de meilleure abstinence que de se priver soi - même et de meilleure (preuve de) distinction que les bonnes manières.",
"Celui qui se vante ( de ses qualités ) auprès des autres se dévalorise aux yeux d’Allah ; celui qui se fait valoir sera humilié par Allah Ta’ala.",
"Le vrai croyant n’est ni un calomniateur ni un parleur éhonté et grossier.",
"Quiconque s’accroche fermement à ma Sounna dans les périodes de corruption aura la récompense de cent martyrs.",
"Une époque viendra où celui qui s’accrochera fermement à sa Religion, sera comparable à celui qui tient un charbon ardent entre les mains.",
"Allah déteste celui qui a la parole facile et qui remue sa langue comme une vache.",
"Que périssent ceux qui font étalage de leur intelligence et qui ont la parole facile.",
"Que celui qui croit en Allah et au Jour dernier parle utilement, ou qu'il se taise.",
"Celui qui garde le silence est sauvé.",
"Restituez les dépôts à ceux qui vous les ont confiés, et ne faites pas d’affaires malhonnêtes avec ceux qui vous trompent.",
"En vérité, le trésorier musulman qui remplit sa tâche avec honnêteté et qui donne scrupuleusement ce qu’il a promis de donner, est l’un des deux hommes charitables ( il sera récompensé pour cela ).",
"Quiconque est sincère envers Allah quarante jours durant, verra un flot de sagesse se déverser de son coeur jusqu’à sa langue.",
"Abandonnez tout ce qui est douteux au profit de ce qui ne l’est pas ; la vérité apporte la paix et le mensonge le doute.",
"De la modération dans les dépenses assure la moitié de la subsistance, l’amour des hommes représente la moitié de la sagesse et les questions intelligentes la moitié de la connaissance.",
"Deux particularités ne se retrouvent jamais chez un hypocrite : une bonne conduite et la compréhension de la religion.",
"Voici les quatre caractéristiques des ambiyaas : la modestie, le fait de se parfumer et de se brosser les dents (utilisation du miswak), le mariage.",
"Je peux jurer de trois choses : la charité ne diminue en rien votre richesse; Allah augmente l’honneur du serviteur qui endure patiemment le mal qu’on lui fait ;quant à celui qui se met à mendier, Il lui ouvre la porte de la pauvreté.",
"Celui qui rend visite à un malade est plongé dans un océan de compassion jusqu’à ce qu’il s’assoie ;quand il est assis, cet océan l’immerge.",
"On n’a pas à faire de voeu ( ou de promesse ) pour ce qui constitue un péché.",
"On n’accomplit pas un voeu dans lequel il y a un péché.",
"La guerre, c’est la stratégie.",
"Il y a une épreuve pour chaque peuple, et celle de mon peuple, c'est la richesse.",
"Celui qui est capable de faire du bien à son frère doit le faire.",
"Chaque personne présente voit ce que les absents ne voient pas.",
"Ce monde est une vaste réserve ( de provisions ) et la meilleure des provisions est une femme vertueuse.",
"Je n’ai laissé derrière moi de plus grande épreuve pour les hommes, qu’une femme.",
"Aucun homme n’est seul avec une femme étrangère sans que Satan ne se trouve en leur compagnie.",
"Je questionnai le prophète au sujet du regard posé soudainement sur une femme. Il me répondit :\"Détournez votre regard.\"",
"Le Prophète a interdit qu’un homme marche entre deux femmes.",
"L’amour pour ce monde est le commencement du péché.",
"Le fils de l’homme s’affaiblit dans son vieil âge; mais deux choses ne cessent d’être jeunes chez lui : son amour pour les biens de ce monde et son désir de vivre longtemps.",
"Le prophète a dit : La prière du Vendredi faite en congrégation est obligatoire pour tous les musulmans à l’exception des esclaves, des femmes, des enfants et des malades.",
"Hazrat Abou Horeira (R. A) rapporte ces propos de l’Envoyé de Dieu : Allah s’engage à aider trois personnes ; tout d’abord, celle qui accomplit la guerre Sainte et s’engage dans le chemin d’Allah ;ensuite, le débiteur qui a l’intention de payer ses dettes ; et enfin, celui qui veut se marier par piété.",
"Hazrat Abou Horeira (R. A) rapporte que Raçouloullah adit : L’homme qui pleure par crainte d A Allah n’ira pas en enfer. Son entrée y est autant impossible que le retour du lait dans le pie de la vache, une fois traite. La poussière du chemin d’Allah et la fumée de l’enfer ne pourront jamais se mélanger.",
"Hazrat Abou Horeira (R. A) rapporte que le prophète a dit que le Mujahid (celui qui combat dans le chemin d’Allah) est l’invité d’Allah. Toutes ses prières sont acceptées.",
"Hazrat Khuzam - bin - Fatek ( R. A ) rapporte ces propos de l’Envoyé de Dieu e. Quiconque dépense dans le chemin d’Allah recevra 700 fois plus (en récompense) de Sa part.",
"Hazrat Aicha ( R. A ), la mère des croyantes, rapporte ceci: Je demandai au prophète l’autorisation de participer au Djihad, mais il me répondit: Ton djihad est l’accomplissement du Hadj.",
"Hazrat Sahi bin Hanif (R. A) raconte que Raçouloullah a dit : Celui qui aspire sincèrement à mourir en martyr sera élevé à ce rang par Allah, même s’il meurt dans son lit.",
"Il n’est pas permis de parler ou de saluer quelqu’un pendant le Khoutbah ( discours du Vendredi ). On rapporte ces propos de l'Envoyé de Dieu : Celui qui parle pendant le Khoutbah est comme un âne chargé de livres.",
"Mes compagnons sont comparables aux étoiles ; quel que soit celui que vous choisissez de suivre, vous serez bien guidés.",
"Toute action dépend de l’intention.",
"Toute action dépend du résultat final. \"Toute bonne action est un acte de charité ( Sadqa ). \"",
"Je suis le dernier prophète il n’y en aura plus aucun autre après moi.",		
};
	
	
private static String[] ref = {
"Mouatta",
"Mouslim",
"Abou Daoud",
"Mouslim",
"Ahmad, Abou Daoud",
"Tirmizi, Ibn Majah",
"Tirmizi",
"Boukhari",
"Tirmizi",
"Tirmizi",
"Ibn Majah",
"Tirmizi",
"[agréé]",
"Tirmizi, Ibn Majah",
"[agréé]",
"Mouslim",
"Tirmizi",
"Tirmizi",
"[agréé]",
"Abou Daoud",
"Tirmizi",
"Abou Daoud",
"Mouslim",
"Mouslim",
"Mouslim",
"[agréé]",
"Abou Daoud, Ahmad",
"Ibn Majah, Tirmizi (rare)",
"Ibn Majah",
"Ibn Majah",
"[agréé]",
"[agréé]",
"Mouslim",
"Ahmad, Abou Daoud",
"Tirmizi (rare)",
"Tirmizi",
"[agréé]",
"Mouslim",
"Abou Daoud",
"Ibn Majah",
"[agréé]",
"Mouslim",
"Ibn Majah",
"[agréé]",
"[agréé]",
"Mouslim",
"[agréé]",
"[agréé]",
"Mouslim",
"Tirmizi",
"Tirmizi",
"Tirmizi",
"Ibn Majah",
"Tirmizi",
"Tirmizi , Abou Daoud",
"Hadith",
"Abou Daoud, Ibn Majah",
"Boukhari",
"[agréé]",
"Mouatta, Ahmad d’Abou Hureira",
"Tirmizi",
"Ahmad",
"Mouslim",
"Boukhari",
"Boukhari",
"Tirmizi, Nasai, Ibn Majah",
"Hadith",
"Hadith",
"Hadith",
"Hadith",
"Hadith",
"Hadith",
"Hadith",
"Hadith",
"Hadith",
"Hadith",
"Hadith",
"Hadith",
"Hadith",
"Hadith",
"Hadith",
"Hadith",
"Mouslim",
"Boukhari, Mouslim",
"Boukhari, Mouslim",
"Mishkat",
"Mishkat",
"Hadith",
"Hadith",
"Boukhari, Mouslim",
"Boukhari, Mouslim",
"Tirmizi",
"Boukhari, Mouslim",
"Boukhari, Mouslim",
"Boukhari",
"Mouslim",
"Tirmizi",
"Mouslim",
"Ibn Majah",
"Boukhari, Mouslim",
"Mouslim",
"Boukhari",
"Boukhari",
"Tirmizi",
"Abou Daoud",
"Abou Daoud",
"Nasai",
"Mouslim",
"Abou Daoud",
"Tirmizi",
"Tirmizi",
"Hadith",
"Mouslim",
"Boukhari, Tirmizi",
"Abou Daoud",
"Tirmizi",
"Abou Daoud",
"Mouslim",
"Bayhaqiy",
"Tirmizi",
"Tirmizi",
"Boukhari",
"Abou Daoud",
"Mouslim",
"Boukhari",
"Boukhari",
"Nasaï",
"Abou daoud",
"Tirmizi",
"Abou Daoud",
"Tirmizi",
"Razin",
"Boukhari",
"Tirmizi",
"Razin",
"Boukhari",
"Abou Daoud",
"Ahmad",
"Abou Daoud",
"Abou Daoud",
"Boukhari",
"Abou Daoud",
"Boukhari",
"Boukhari",
"Boukhari",
"Tirmizi",
"Ibn Majah",
"Musllm",
"Musllm",
"Tirmizi",
"Tirmizi",
"Mouslim",
"Boukhari",
"Mallk",
"Tirmizi",
"Boukhari",
"Mouslim",
"Tirmizi",
"Tirmizi",
"Musllm",
"Abou Daoud",
"Boukhari",
"Ahmad",
"Tirmlzl",
"Baghawiy",
"Boukhari",
"Boukhari",
"Boukhari",
"Abou Daoud",
"Tirmizi",
"Boukhari",
"Boukhari",
"Tirmizi",
"Tirmizi",
"Mouslim",
"Boukhari",
"Boukhari",
"Boukhari",
"Bayhaqiy",
"Mouslim",
"Abou Daoud",
"Boukhari",
"Abou Daoud",
"Tirmizi",
"Bayhaqiy",
"Abou Daoud",
"Tirmizi",
"Bukharl",
"Abou Daoud",
"Bayhaqiy",
"Bayhaqiy",
"Boukhari",
"Tirmizi",
"Tirmizi",
"Ahmad",
"Mouslim",
"Boukhari",
"Tirmizi",
"Ahmad",
"Tirmizi",
"Abou Daoud",
"Boukhari",
"Boukhari",
"Tirmizi",
"Abou Daoud",
"Abou Daoud",
"Boukhari",
"Tirmizi",
"Darimiy",
"Nasaï",
"Tirmizi",
"Abou Daoud",
"Tirmizi",
"Boukhari",
"Tirmizi",
"Bayhaqiy",
"Tirmizi",
"Bayhaqiy",
"Bokhari",
"Tirmizi",
"Bayhaqiy",
"Tirmizi",
"Tirmizi",
"Mouslim",
"Tirmizi",
"Tirmizi",
"Abou Daoud",
"Boukhari",
"Razin",
"Tirmizi",
"Bayhaqiy",
"Tirmizi",
"Tirmizi",
"Tirmizi",
"Malik",
"Abou Daoud",
"Mouslim",
"Abou Daoud",
"Tirmizi",
"Mouslim",
"Mouslim",
"?",
"Nasaï",
"?",
"Mouslim",
"Abou Daoud",
"Abou Daoud",
"Boukhari",
"Abou Daoud",
"Tirmizi",
"Tirmizi",
"Ibn Majah",
"Tirmizi, Nasaï",
"Boukhari",
"Mouslim",
"Ahmad",
"Mishkaat, Baboul-Manaqib",
"Boukhari, Mouslim",
"Boukhari, Mouslim",
"Boukhari, Mouslim"};
	*/
}
